### ISSUE TITLE
yet another javafx

### ISSUE THREAD

**Issue by BebSxy** [java-deobfuscator/deobfuscator-gui#63] opened 2023-01-04 02:59 UTC
https://cdn.discordapp.com/attachments/1049200483975303222/1060025669658103839/image.png

**Comment by Janmm14** [comment] 2023-01-04 14:20
Duplicate of #43 
In case that does not resolve the issue for you, please make sure you are using the latest version.
If you have further issues with the gui (not the deobfuscation), feel free to ask here.

**Closed as completed by Janmm14** 2023-01-04 14:20 UTC
